# Generated by Django 4.2.3 on 2023-08-04 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ItemImage/', verbose_name='Item Image')),
                ('iin', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='IIN')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Quantity Sold')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('profit_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit Earned')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('transactiondttm', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date and Time')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Item')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('orderdttm', models.DateTimeField(auto_now_add=True, verbose_name='Order Date and Time')),
                ('is_received', models.BooleanField(default=False, verbose_name='Is Received')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='Is Cancelled')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Item')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
